{
 "title": "Тритон метрики",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Аналитика времени", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Среднее время выполнения одного запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (model,version)(\r\n  increase(nv_inference_compute_infer_duration_us{\r\n    job=\"triton\"\r\n  }[10s])\r\n))\r\n/ \r\n(\r\n  sum by (model,version)\r\n(\r\nincrease(nv_inference_request_success{\r\n  job=\"triton\"\r\n}[10s])\r\n))\r\n/ 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время ожидания запроса в очереди",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (model,version) (\r\n  rate(nv_inference_queue_duration_us{job=\"triton\"}[10s])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Аналитика запросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Число инференсов (кадров/видосов) в секунду (FPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"triton\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число запросов к тритону в секунду (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_success{job=\"triton\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер батча",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"triton\"}[10s])/rate(nv_inference_exec_count{job=\"triton\"}[10s]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Сколько раз обращались к модели (amount/batch_size) с момента старта тритона",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "nv_inference_exec_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Число инференсов (число прогнанных кадров/видосов) с момента старта тритона",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "expr": "nv_inference_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Число успешных запросов по апи с момента старта тритона",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Число падений запросов с момента старта тритона",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    { "expr": "nv_inference_request_failure", "legendFormat": "__auto" }
   ]
  },
  { "title": "Аналитика утилизации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Доля GPU утилизации памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU потребление энергии",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by (gpu_uuid) (rate(nv_energy_consumption{job=\"triton\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Занятая память GPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (gpu_uuid) (\r\n  nv_gpu_memory_used_bytes{job=\"triton\"}\r\n) / (1024^3)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}